--liquibase formatted sql
--changeset mtg:1

CREATE TABLE PLAYER (
    NAME VARCHAR(255) PRIMARY KEY
);

CREATE TABLE DECK (
    NAME VARCHAR(255) PRIMARY KEY,
    PLAYER_NAME VARCHAR(255) NOT NULL,
    CONSTRAINT FK_PLAYER_NAME FOREIGN KEY (PLAYER_NAME) REFERENCES PLAYER(NAME)
);